import Workflow from '../types/Workflow';
import Job from '../types/Job';
import Step from '../types/Step';
import RunTestsJob from '../types/jobs/RunTestsJob';
import CheckoutStep from '../types/steps/CheckoutStep';

// Assuming you have a YAML defining a workflow, this file can be generated by running `npx convert-workflows`.
// Now, when it's in TypeScript format, you can modify it, use it in other workflows, etc.
// Finally, convert this file back into a YAML workflow using `npx generate-workflow-files build`

export const workflow = new Workflow('test-workflow', {
  name: 'Run tests',
  on: 'push',
  jobs: [
    new Job('build', {
      steps: [
        new CheckoutStep(),
        new Step({ run: ["echo 'Success!'", "echo 'Checkout step is done'"] }),
      ],
    }),
    new RunTestsJob(),
  ],
});
